src/controllers/CarouselController.php
<?php

namespace werewolf8904\cmsdbwidgets\controllers;


use werewolf8904\cmscore\controllers\BackendController;
use werewolf8904\cmsdbwidgets\models\backend\Carousel;
use werewolf8904\cmsdbwidgets\models\backend\search\CarouselSearch;
use werewolf8904\cmsdbwidgets\services\CarouselService;


/**
 * WidgetCarouselController implements the CRUD actions for WidgetCarousel model.
 */
class CarouselController extends BackendController
{
    public $searchClass = CarouselSearch::class;
    public $compositeService = CarouselService::class;
    public $class = Carousel::class;

}

src/controllers/CarouselItemController.php
<?php

namespace werewolf8904\cmsdbwidgets\controllers;

use werewolf8904\cmscore\models\Language;
use werewolf8904\cmsdbwidgets\models\backend\CarouselItem;
use werewolf8904\cmsdbwidgets\models\base\Carousel;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;


/**
 * WidgetCarouselItemController implements the CRUD actions for WidgetCarouselItem model.
 */
class CarouselItemController extends Controller
{

    /**
     * @return string
     */
    public function getViewPath()
    {
        return $this->module->getViewPath() . DIRECTORY_SEPARATOR . 'carousel/item';
    }


    /**
     * Creates a new WidgetCarouselItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @param $carousel_id
     *
     * @return string|\yii\web\Response
     * @throws \yii\base\InvalidArgumentException
     * @throws HttpException
     */
    public function actionCreate($carousel_id)
    {
        $model = new CarouselItem();
        $carousel = Carousel::findOne($carousel_id);
        if (!$carousel) {
            throw new HttpException(400);
        }

        $model->carousel_id = $carousel->id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('alert', ['options' => ['class' => 'alert-success'], 'body' => Yii::t('dbwidgets', 'Carousel slide was successfully saved')]);
            return $this->redirect(['carousel/update', 'id' => $model->carousel_id]);
        }
        $view_params = compact('model', 'carousel');
        $view_params['languages'] = Language::find()->andWhere(['status'=>1])->all();
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('create', $view_params);
        }
        return $this->render('create', $view_params);
    }

    /**
     * Updates an existing WidgetCarouselItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws \yii\base\InvalidArgumentException
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('alert', ['options' => ['class' => 'alert-success'], 'body' => Yii::t('dbwidgets', 'Carousel slide was successfully saved')]);
            if (!Yii::$app->request->isAjax) {
                return $this->redirect(['carousel/update', 'id' => $model->carousel_id]);
            }

        }
        $view_params = compact('model');
        $view_params['languages'] = Language::find()->andWhere(['status'=>1])->all();
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('update', $view_params);
        }
        return $this->render('update', $view_params);
    }

    /**
     * Finds the WidgetCarouselItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return CarouselItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CarouselItem::find()->where(['id' => $id])->with(['translations'])->one()) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Deletes an existing WidgetCarouselItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model && $model->delete()) {
            return $this->redirect(['carousel/update', 'id' => $model->carousel_id,]);
        }

        throw new BadRequestHttpException();
    }
}

src/controllers/ImageController.php
<?php

namespace werewolf8904\cmsdbwidgets\controllers;


use werewolf8904\cmscore\controllers\BackendController;
use werewolf8904\cmsdbwidgets\models\backend\Image;
use werewolf8904\cmsdbwidgets\models\backend\search\ImageSearch;


/**
 * WidgetImageController implements the CRUD actions for WidgetImage model.
 */
class ImageController extends BackendController
{

    public $searchClass = ImageSearch::class;
    public $class = Image::class;
}

src/controllers/MenuController.php
<?php

namespace werewolf8904\cmsdbwidgets\controllers;


use werewolf8904\cmscore\controllers\BackendController;
use werewolf8904\cmsdbwidgets\models\backend\search\MenuSearch;
use werewolf8904\cmsdbwidgets\models\base\Menu;
use werewolf8904\cmsdbwidgets\services\MenuService;


/**
 * WidgetCarouselController implements the CRUD actions for WidgetCarousel model.
 */
class MenuController extends BackendController
{
    public $searchClass = MenuSearch::class;
    public $compositeService = MenuService::class;
    public $class = Menu::class;

}

src/controllers/TextController.php
<?php

namespace werewolf8904\cmsdbwidgets\controllers;


use werewolf8904\cmscore\controllers\BackendController;
use werewolf8904\cmsdbwidgets\models\backend\search\TextSearch;
use werewolf8904\cmsdbwidgets\models\backend\Text;


/**
 * WidgetTextController implements the CRUD actions for WidgetText model.
 */
class TextController extends BackendController
{
    public $searchClass = TextSearch::class;
    public $class = Text::class;
}

src/views/carousel/_form.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\composite\base\CompositeForm $model
 * @var yii\bootstrap\ActiveForm $form
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>
<div id="color-dialog" role="dialog" class="modal my-modal fade popup" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <output id="ajax_content"></output>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <?= Yii::t('backend', 'Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="widget-carousel-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <?= $form->field($model->modelCarousel, 'key')->textInput(['maxlength' => 1024]) ?>
    <?= $form->field($model->modelCarousel, 'status')->checkbox(); ?>
    <hr>
    <?php
    $items = [];
    foreach ($languages as $language) {
        $items[] = [
            'name' => Yii::$app->language === $language->code ? 'image' : 'image_' . $language->code,
            'title' => Yii::t('cmsdbwidgets/model_labels', 'Image') . ' ' . $language->code,
            'type' => \alexantr\elfinder\InputFile::class,
            'options' => [
                'clientRoute' => '//file/manager/input',
                'options' => [
                    'class' => 'form-control yii2-elfinder-input input_preview',
                    'data' => [
                        'default-src' => '/no_image.png',
                        'storage-src' => Yii::getAlias('@storageUrl/source')
                    ],
                ],
            ],
        ];
        $items[] = [
            'name' => Yii::$app->language === $language->code ? 'alt' : 'alt_' . $language->code,
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_HIDDEN_INPUT,
            'enableError' => true,
        ];
        $items[] = [
            'name' => Yii::$app->language === $language->code ? 'content' : 'content_' . $language->code,
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_HIDDEN_INPUT,
            'enableError' => true,
        ];
        $items[] = [
            'name' => Yii::$app->language === $language->code ? 'url' : 'url_' . $language->code,
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_HIDDEN_INPUT,
            'enableError' => true,
        ];
        $items[] = [
            'name' => Yii::$app->language === $language->code ? 'title' : 'title_' . $language->code,
            'title' => Yii::t('cmsdbwidgets/model_labels', 'Title') . ' ' . $language->code,
        ];
    }
    $columns = [
        [
            'name' => 'id',
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_HIDDEN_INPUT,
            'enableError' => true,
        ],
        [
            'name' => 'id',
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_STATIC,
            'value' => function ($value) {
                if ($value && $value->id) {
                    $template = '<a href="' . \yii\helpers\Url::toRoute(['carousel-item/update', 'id' => $value->id,]) . '"><span class="glyphicon glyphicon-pencil"></span></a>';
                    //$template .= '<span></span><a href="' . \yii\helpers\Url::toRoute(['carousel-item/update', 'id' => $value->id,]) . '" class="ajax"><span class="glyphicon glyphicon-edit"></span></a>';
                    return $template;
                }
                return '';
            },
        ],
        [
            'name' => 'status',
            'title' => Yii::t('cmsdbwidgets/model_labels', 'Status'),
            'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_CHECKBOX,
        ]
    ];
    $columns = array_merge($columns, $items);
    echo $form->field($model, 'modelsItem')->widget(\unclead\multipleinput\MultipleInput::class, [
        'min' => 0,
        'sortable' => true,
        'columns' => $columns,
    ]);
    ?>
    <div class="form-group">
        <?= Html::submitButton($model->modelCarousel->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->modelCarousel->isNewRecord ? 'btn btn-success' : 'btn btn-primary',]) ?>
        <?= Html::submitButton(Yii::t('backend', 'Save and stay'), ['class' => 'btn btn-success', 'name' => 'stay',]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

src/views/carousel/create.php
<?php
/**
 * @var yii\web\View $this
 * @var werewolf8904\cmsdbwidgets\models\base\Carousel $model
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => Yii::t('backend', 'Widget Carousel'),
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Carousels'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="widget-carousel-create">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/carousel/index.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\search\CarouselSearch $searchModel
 * @var yii\data\ActiveDataProvider $dataProvider
 */

use kartik\editable\Editable;
use kartik\grid\EditableColumn;
use kartik\grid\GridView;
use yii\grid\SerialColumn;

$columns = [
    ['class' => SerialColumn::class],
    'id',
    'key',
    [
        'class' => EditableColumn::class,
        'attribute' => 'status',
        'filter' => [
            Yii::t('backend', 'Not Published'),
            Yii::t('backend', 'Published'),
        ],
        'vAlign' => 'middle',
        'editableOptions' => [
            'format' => Editable::FORMAT_BUTTON,
            'displayValueConfig' => ['0' => GridView::ICON_INACTIVE, '1' => GridView::ICON_ACTIVE],
            'inputType' => \kartik\editable\Editable::INPUT_SWITCH,
            'placement' => 'auto',
        ],
    ],
]; ?>
<?= $this->render('@core/views/_common/index', [
    'columns' => $columns,
    'title' => Yii::t('backend', 'Widget Carousels'),
    'title_create' => Yii::t('backend', 'Widget Carousel'),
    'dataProvider' => $dataProvider,
    'searchModel' => $searchModel
]) ?>

src/views/carousel/item/_form.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\CarouselItem $model
 * @var yii\bootstrap\ActiveForm $form
 * */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>
<div class="widget-carousel-item-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model) ?>
    <?= $form->field($model, 'status')->checkbox(); ?>
    <?= $form->field($model, 'sort')->textInput(); ?>
    <hr>
    <?= \yii\bootstrap\Tabs::widget([
        'items' => \yii\helpers\ArrayHelper::getColumn(
            $languages,
            function ($language) use ($form, $model) {
                /**
                 * @var \werewolf8904\cmscore\models\Language $language
                 */
                return [
                    'label' => $language->name,
                    'content' => $this->render('_form_i18n', compact('form', 'model', 'language'))
                ];
            },
            false
        ),
    ]); ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary',]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

src/views/carousel/item/_form_i18n.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\CarouselItem $model
 * @var yii\bootstrap\ActiveForm $form
 * @var \werewolf8904\cmscore\models\Language $language
 */

echo $form->field($model, $model->defaultLanguage === $language->code ? 'image' : 'image_' . $language->code)
    ->widget(\alexantr\elfinder\InputFile::class, [
        'clientRoute' => '//file/manager/input',
        'options' => [
            'class' => ['form-control', 'yii2-elfinder-input', 'input_preview',],
            'data' => [
                'default-src' => '/no_image.png',
                'storage-src' => Yii::getAlias('@storageUrl/source')
            ],
        ],
    ])->label($model->getAttributeLabel('image'));
echo $form->field($model, $model->defaultLanguage === $language->code ? 'image_media' : 'image_media_' . $language->code)
    ->widget(\unclead\multipleinput\MultipleInput::class, [
        'min' => 0,
        'sortable' => true,
        'columns' => [
            [
                'name' => 'image',
                'type' => \alexantr\elfinder\InputFile::class,
                'options' => [
                    'clientRoute' => '//file/manager/input',
                    'options' => [
                        'class' => ['form-control', 'yii2-elfinder-input', 'input_preview',],
                        'data' => [
                            'default-src' => '/no_image.png',
                            'storage-src' => Yii::getAlias('@storageUrl/source')
                        ],
                    ],
                ],
            ],
            [
                'name' => 'media',
                'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_DROPDOWN,
                'items' => \werewolf8904\cmsdbwidgets\helpers\Media::getList(),
            ],
        ],
    ])->label($model->getAttributeLabel('image_media'));
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'content' : 'content_' . $language->code
)->label($model->getAttributeLabel('content'))->widget(\alexantr\ckeditor\CKEditor::class);
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'title' : 'title_' . $language->code
)->label($model->getAttributeLabel('title'));
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'alt' : 'alt_' . $language->code
)->label($model->getAttributeLabel('alt'));
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'url' : 'url_' . $language->code
)->label($model->getAttributeLabel('url'))->textInput();

src/views/carousel/item/create.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\CarouselItem $model
 * @var werewolf8904\cmsdbwidgets\models\base\Carousel $carousel
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => Yii::t('backend', 'Widget Carousel Item')
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Carousel Items'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = ['label' => $carousel->key, 'url' => ['update', 'id' => $carousel->id,],];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Create');
?>
<div class="widget-carousel-item-create">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/carousel/item/update.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\CarouselItem $model
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
        'modelClass' => Yii::t('backend', 'Widget Carousel Item'),
    ]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Carousel Items'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = ['label' => $model->carousel->key, 'url' => ['widget-carousel/update', 'id' => $model->carousel->id,],];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="widget-carousel-item-update">
    <?php \yii\widgets\Pjax::begin(['enablePushState' => false, 'id' => $model->id,]) ?>
    <?= $this->render('_form', compact('model', 'languages')) ?>
    <?php \yii\widgets\Pjax::end() ?>
</div>

src/views/carousel/update.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\composite\base\CompositeForm $model
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
        'modelClass' => Yii::t('backend', 'Widget Carousel'),
    ]) . ' ' . $model->modelCarousel->key;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Carousels'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = ['label' => $model->modelCarousel->key,];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="widget-carousel-update">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/image/_form.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\Image $model
 * @var yii\bootstrap\ActiveForm $form
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Tabs;
use yii\helpers\Html;

?>
<div class="widget-image-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->errorSummary($model); ?>
    <?= $form->field($model, 'key')->textInput(['maxlength' => true,]) ?>
    <?= $form->field($model, 'status')->checkbox(); ?>
    <hr>
    <?= Tabs::widget([
        'items' => \yii\helpers\ArrayHelper::getColumn(
            $languages,
            function ($language) use ($form, $model) {
                /**
                 * @var \werewolf8904\cmscore\models\Language $language
                 */
                return [
                    'label' => $language->name,
                    'content' => $this->render('_form_i18n', compact('form', 'model', 'language'))
                ];
            },
            false
        )
    ]); ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary',]) ?>
        <?= Html::submitButton(Yii::t('backend', 'Save and stay'), ['class' => 'btn btn-success', 'name' => 'stay',]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

src/views/image/_form_i18n.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\Image $model
 * @var yii\bootstrap\ActiveForm $form
 * @var \werewolf8904\cmscore\models\Language $language
 */

echo $form->field($model, $model->defaultLanguage === $language->code ? 'image' : 'image_' . $language->code)->widget(\alexantr\elfinder\InputFile::class, [
    'clientRoute' => '//file/manager/input',
    'options' => [
        'class' => 'form-control yii2-elfinder-input input_preview',
        'data' => [
            'default-src' => '/no_image.png',
            'storage-src' => Yii::getAlias('@storageUrl/source'),
        ],
    ],
])->label($model->getAttributeLabel('image'));
echo $form->field($model, $model->defaultLanguage === $language->code ? 'image_media' : 'image_media_' . $language->code)
    ->widget(\unclead\multipleinput\MultipleInput::class, [
        'min' => 0,
        'sortable' => true,
        'columns' => [
            [
                'name' => 'image',
                'type' => \alexantr\elfinder\InputFile::class,
                'options' => [
                    'clientRoute' => '//file/manager/input',
                    'options' => [
                        'class' => ['form-control', 'yii2-elfinder-input', 'input_preview',],
                        'data' => [
                            'default-src' => '/no_image.png',
                            'storage-src' => Yii::getAlias('@storageUrl/source'),
                        ],
                    ],
                ],
            ],
            [
                'name' => 'media',
                'type' => \unclead\multipleinput\MultipleInputColumn::TYPE_DROPDOWN,
                'items' => \werewolf8904\cmsdbwidgets\helpers\Media::getList(),
            ],
        ],
    ])->label($model->getAttributeLabel('image_media'));
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'title' : 'title_' . $language->code
)->label($model->getAttributeLabel('title'));
echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'alt' : 'alt_' . $language->code
)->label($model->getAttributeLabel('alt'));

echo $form->field(
    $model,
    $model->defaultLanguage === $language->code ? 'url' : 'url_' . $language->code
)->label($model->getAttributeLabel('url'))->textInput();

src/views/image/create.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\Image $model
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => Yii::t('backend', 'Widget Image'),
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Images'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="widget-image-create">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/image/index.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\search\ImageSearch $searchModel
 * @var yii\data\ActiveDataProvider $dataProvider
 */

use kartik\editable\Editable;
use kartik\grid\EditableColumn;
use kartik\grid\GridView;
use yii\grid\SerialColumn;

$columns = [
    ['class' => SerialColumn::class,],
    'id',
    'key',
    [
        'class' => EditableColumn::class,
        'attribute' => 'status',
        'filter' => [
            Yii::t('backend', 'Not Published'),
            Yii::t('backend', 'Published'),
        ],
        'vAlign' => 'middle',
        'editableOptions' => [
            'format' => Editable::FORMAT_BUTTON,
            'displayValueConfig' => ['0' => GridView::ICON_INACTIVE, '1' => GridView::ICON_ACTIVE,],
            'inputType' => \kartik\editable\Editable::INPUT_SWITCH,
            'placement' => 'auto',
        ],
    ],
]; ?>
<?= $this->render('@core/views/_common/index', [
    'columns' => $columns,
    'title' => Yii::t('backend', 'Widget Image'),
    'title_create' => Yii::t('backend', 'Widget Image'),
    'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]) ?>

src/views/image/update.php
<?php
/**
 * @var yii\web\View $this
 * @var \werewolf8904\cmsdbwidgets\models\backend\Image $model
 * @var \werewolf8904\cmscore\models\Language[] $languages
 */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
        'modelClass' => Yii::t('backend', 'Widget Image'),
    ]) . ' ' . $model->key;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Images'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = ['label' => $model->key,];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="widget-image-update">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/menu/create.php
<?php
/**
 * @var $this yii\web\View
 * @var $model werewolf8904\cmsdbwidgets\models\base\Carousel
 * @var $languages \werewolf8904\cmscore\models\Language[]
 */

$this->title = Yii::t('backend', 'Create {modelClass}', [
    'modelClass' => Yii::t('backend', 'Widget Carousel'),
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Widget Carousels'), 'url' => ['index',],];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="widget-carousel-create">
    <?= $this->render('_form', compact('model', 'languages')) ?>
</div>

src/views/menu/index.php
<?php
/**
 * @var $this yii\web\View
 * @var $searchModel \werewolf8904\cmsdbwidgets\models\backend\search\MenuSearch
 * @var $dataProvider yii\data\ActiveDataProvider
 */

use kartik\editable\Editable;
use kartik\grid\EditableColumn;
use kartik\grid\GridView;
use yii\grid\SerialColumn;

$columns = [
    ['class' => SerialColumn::class,],
    'key',
    [
        'class' => EditableColumn::class,
        'attribute' => 'status',
        'filter' => [
            Yii::t('backend', 'Not Published'),
            Yii::t('backend', 'Published'),
        ],
        'vAlign' => 'middle',
        'editableOptions' => [
            'format' => Editable::FORMAT_BUTTON,
            'displayValueConfig' => ['0' => GridView::ICON_INACTIVE, '1' => GridView::ICON_ACTIVE,],
            'inputType' => \kartik\editable\Editable::INPUT_SWITCH,
            'placement' => 'auto',
        ],
    ],
]; ?>
<?= $this->render('@core/views/_common/index', [
    'columns' => $columns,
    'title' => Yii::t('backend', 'Widget Menus'),
    'title_create' => Yii::t('backend', 'Widget Menu'),
    'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]) ?>